spring.application.name = linkit
spring.datasource.url = jdbc:postgresql://localhost:5432/linkit
spring.datasource.username = linkit
spring.datasource.password = linkit
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update